name: Your_first_workflow
on:
  push:
    branches: [ "main" ]

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: List and Read files
              run: |
                echo "My first workflow"
                ls -ltra
                cat README.md
              