name: Generate ASCII Art
on:
    push:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install the cowsay cli
              run: |
                sudo apt-get update -y
                sudo apt-get install cowsay -y

            - name: Execute cowsay command
              run: cowsay -f dragon "Fear me for I am Vagar.. Raaahh!!" >> dragon.txt

            - name: upload artifact file
              uses: actions/upload-artifact@v4
              with:
                name: dragon_file
                path: dragon.txt

    test_job:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon_file

            - name: Check if file exists
              run: ls | grep -i "dragon"

    deploy:
        needs: test_job
        runs-on: ubuntu-lastes
        steps:
            - name: Download the dragon file
              uses: actions/download-artifact@v4
              with:
                name: dragon_file
            
            - name: Execute the dragon
              run: cat dragon.txt

            - name: Deploy
              run: echo "Deploying"