name: Matrix Example
on:
    push:
         
        branches: [ "main" ]
    workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest,ubuntu-20.04,windows-latest]
        images: [hello-world,alpine]
        exclude:
            - images: alpine
              os: windows-latest
        include:
            - image: nginx
              os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info

      - name: Run images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}