name: Matrix Example
on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-20.04,windows-latest]
        images: [docker,alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info

      - name: Run images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}